To activate a virtual environment
   source venv/bin/activate

Type deactivate to exit


requirements.txt 
      pip3 freeze > requirements.txt


When cloning and running someone else's github
      pip3 install -r requirements.txt

Matching Resumes to Job Opportunities Using Python
    https://www.google.com/search?q=resume+matching+with+job+description+python&sca_esv=a5ad54a154ad8b44&sxsrf=ANbL-n7IrNDrZtTNwsgLRpojSy5Ume4bNA%3A1775425076691&ei=NNbSaY7-Kdm0wN4P88LswA4&oq=how+to+build+a+python+program+to+match+resume+to+job+description&gs_lp=Egxnd3Mtd2l6LXNlcnAiQGhvdyB0byBidWlsZCBhIHB5dGhvbiBwcm9ncmFtIHRvIG1hdGNoIHJlc3VtZSB0byBqb2IgZGVzY3JpcHRpb24qAggAMgoQABhHGNYEGLADMgoQABhHGNYEGLADMgoQABhHGNYEGLADMgoQABhHGNYEGLADMgoQABhHGNYEGLADMgoQABhHGNYEGLADMgoQABhHGNYEGLADMgoQABhHGNYEGLADSKclUABYAHABeACQAQCYAUigAUiqAQExuAEDyAEAmAIBoAIGmAMAiAYBkAYIkgcBMaAHwAWyBwC4BwDCBwMyLTHIBwSACAE&sclient=gws-wiz-serp#fpstate=ive&vld=cid:8589b67f,vid:PfNalySVhoY,st:0

In [17]:
# is this needed?

headers = { 
    'User-Agent':
'MyDataAnalystJobScraper/1.0 (Contact: jmasters0013@me.com)'
}

In [16]:
import requests
import pandas as pd 
import os
import PyPDF2
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity 

response = requests.get(
    "https://remoteok.com/api",
    headers={"User-Agent": "Mozilla/5.0"}
)

jobs = response.json()

In [9]:
if response.status_code == 200:
    jobs = response.json()
    print(f"Successfully retrieved {len(jobs)} jobs listings!")
else:
    print(f"Failed to retrieve data. Status Code: {respose.status_code}")

Successfully retrieved 98 jobs listings!

In [10]:
remote_ok = pd.DataFrame(jobs)
remote_ok.head(10)

,last_updated,legal,slug,id,epoch,date,company,company_logo,position,tags,description,location,apply_url,salary_min,salary_max,logo,url,original,verified
0,1.775347e+09,API Terms of Service: Please link back (with f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,remote-senior-site-civil-engineer-land-develop...,1130993,1.775318e+09,2026-04-04T16:00:06+00:00,"ms consultants, inc.",,Senior Site Civil Engineer Land Development,"[design, 3d, consulting, support, software, ma...","<p>\n</p><p style=""margin: 0in; line-height: 1...",,https://remoteOK.com/remote-jobs/remote-senior...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-senior...,NaN,NaN
2,NaN,NaN,remote-senior-ux-ui-designer-gomining-1130992,1130992,1.775232e+09,2026-04-03T16:00:12+00:00,GoMining,,Senior UX UI designer,"[ui, ux, design, designer, support, developer,...",<p>We are looking for aÂ Senior UX/UI Designer...,,https://remoteOK.com/remote-jobs/remote-senior...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-senior...,NaN,NaN
3,NaN,NaN,remote-legal-counsel-ai-trainer-freelance-8-20...,1130991,1.775232e+09,2026-04-03T16:00:04+00:00,10x Team,,Legal Counsel AI Trainer Freelance 8 20 hrs week,"[trainer, consulting, test, legal, non tech]","<p style=""min-height:1.5em"">Updated: 03 April ...",Bucharest,https://remoteOK.com/remote-jobs/remote-legal-...,84.0,180.0,,https://remoteOK.com/remote-jobs/remote-legal-...,NaN,NaN
4,NaN,NaN,remote-senior-sales-development-representative...,1130989,1.775174e+09,2026-04-03T00:00:03+00:00,Huzzle,,Senior Sales Development Representative,"[saas, system, support, testing, lead, senior,...","About Huzzle<p>At Huzzle, we connect high-perf...",,https://remoteOK.com/remote-jobs/remote-senior...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-senior...,NaN,NaN
5,NaN,NaN,remote-website-maintenance-crewbloom-1130987,1130987,1.775146e+09,2026-04-02T16:01:26+00:00,CrewBloom,,Website Maintenance,"[system, technical, support, seo, recruiting]",<p>Weâre looking for a detail-oriented Websi...,,https://remoteOK.com/remote-jobs/remote-websit...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-websit...,NaN,NaN
6,NaN,NaN,remote-lead-consultant-public-sector-celonis-1...,1130986,1.775146e+09,2026-04-02T16:01:20+00:00,Celonis,,Lead Consultant Public Sector,"[consultant, saas, consulting, technical, supp...","We're Celonis, the global leader in Process In...",Washington DC,https://remoteOK.com/remote-jobs/remote-lead-c...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-lead-c...,NaN,NaN
7,NaN,NaN,remote-product-manager-energy-storage-controls...,1130985,1.775146e+09,2026-04-02T16:01:10+00:00,Verse,,Product Manager Energy Storage Controls & Tele...,"[manager, software, travel, cloud, operations,...","<p><strong>Location: </strong>San Francisco, C...","San Francisco, CA",https://remoteOK.com/remote-jobs/remote-produc...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-produc...,NaN,NaN
8,NaN,NaN,remote-sales-development-representative-huzzle...,1130984,1.775146e+09,2026-04-02T16:00:55+00:00,Huzzle,,Sales Development Representative,"[salesforce, training, growth, lead, marketing...","About Huzzle<p>At Huzzle, we connect exception...",,https://remoteOK.com/remote-jobs/remote-sales-...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-sales-...,NaN,NaN
9,NaN,NaN,remote-senior-strategist-future-of-work-ai-rea...,1130983,1.775146e+09,2026-04-02T16:00:39+00:00,American Institutes for Research,,Senior Strategist Future of Work & AI Readiness,"[design, system, strategist, support, senior, ...",AIR is seeking a Senior Work & AI Strategist t...,,https://remoteOK.com/remote-jobs/remote-senior...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-senior...,NaN,NaN

In [13]:
remote_ok.tail(10)

,last_updated,legal,slug,id,epoch,date,company,company_logo,position,tags,description,location,apply_url,salary_min,salary_max,logo,url,original,verified
88,NaN,NaN,remote-senior-talent-acquisition-coordinator-n...,1130890,1.774541e+09,2026-03-26T16:00:46+00:00,New Relic,,Senior Talent Acquisition Coordinator,"[coordinator, video, senior, non tech]",We are a global team of innovators and pioneer...,Hyderabad,https://remoteOK.com/remote-jobs/remote-senior...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-senior...,NaN,NaN
89,NaN,NaN,remote-studio-manager-vox-media-llc-1130889,1130889,1.774541e+09,2026-03-26T16:00:38+00:00,"Vox Media, LLC",,Studio Manager,"[manager, technical, support, video, managemen...","Vox Media is seeking a proactive, highly organ...","New York, New York",https://remoteOK.com/remote-jobs/remote-studio...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-studio...,NaN,NaN
90,NaN,NaN,remote-senior-product-manager-checkout-post-bo...,1130888,1.774541e+09,2026-03-26T16:00:28+00:00,Tripadvisor,,Senior Product Manager Checkout & Post Booking,"[manager, testing, travel, lead, senior, non t...","<p><strong><em>Senior Product Manager, Checkou...",POL Virtual,https://remoteOK.com/remote-jobs/remote-senior...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-senior...,NaN,NaN
91,NaN,NaN,remote-outbound-account-executive-us-amplemark...,1130887,1.774541e+09,2026-03-26T16:00:18+00:00,Amplemarket,,Outbound Account Executive US,"[lead, sales, executive]",What is Amplemarket all about?\nAmplemarket's ...,"Remote, US",https://remoteOK.com/remote-jobs/remote-outbou...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-outbou...,NaN,NaN
92,NaN,NaN,remote-commercial-associate-molecule-xyz-1130884,1130884,1.774512e+09,2026-03-26T08:00:08+00:00,molecule.xyz,,Commercial Associate,"[web3, system, ceo, investor, sales, biotech]","<p style=""min-height:1.5em"">Molecule and BIO.x...",,https://remoteOK.com/remote-jobs/remote-commer...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-commer...,NaN,NaN
93,NaN,NaN,remote-ads-video-editor-for-dtc-group-paired-1...,1130883,1.774512e+09,2026-03-26T08:00:02+00:00,Paired,,Ads Video Editor for DTC Group,"[support, testing, video, ads, content, recrui...",<p>Paired is a global staffing and recruiting ...,,https://remoteOK.com/remote-jobs/remote-ads-vi...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-ads-vi...,NaN,NaN
94,NaN,NaN,remote-staff-accountant-latam-hirehawk-1130882,1130882,1.774483e+09,2026-03-26T00:01:02+00:00,HireHawk,,Staff Accountant LATAM,[accountant],"Job Type: Full-time, long-term contractorWorkp...",,https://remoteOK.com/remote-jobs/remote-staff-...,1300.0,1900.0,,https://remoteOK.com/remote-jobs/remote-staff-...,NaN,NaN
95,NaN,NaN,remote-senior-developer-backend-search-cd-e-ub...,1130881,1.774483e+09,2026-03-26T00:00:53+00:00,Ubiminds,,Senior Developer Backend Search CD+E,"[developer, design, hr, frontend, technical, r...","<p><span style=""font-size: 32px;"">Info on the ...",Remote,https://remoteOK.com/remote-jobs/remote-senior...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-senior...,NaN,NaN
96,NaN,NaN,remote-interior-designer-bold-business-1130880,1130880,1.774483e+09,2026-03-26T00:00:30+00:00,Bold Business,,Interior Designer,"[design, designer, support, code, part-time, d...",<div><h2><strong>Role Summary</strong></h2>\n<...,"India, Philippines",https://remoteOK.com/remote-jobs/remote-interi...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-interi...,NaN,NaN
97,NaN,NaN,remote-pmhnp-clinical-autonomy-total-flexibili...,1130879,1.774483e+09,2026-03-26T00:00:20+00:00,Seasoned Recruitment,,PMHNP Clinical Autonomy & Total Flexibility,"[management, recruiter, non tech]",The Role: Care Without the ClutterAre you a Bo...,,https://remoteOK.com/remote-jobs/remote-pmhnp-...,0.0,0.0,,https://remoteOK.com/remote-jobs/remote-pmhnp-...,NaN,NaN

In [15]:
remote_ok.columns

Index(['last_updated', 'legal', 'slug', 'id', 'epoch', 'date', 'company',
       'company_logo', 'position', 'tags', 'description', 'location',
       'apply_url', 'salary_min', 'salary_max', 'logo', 'url', 'original',
       'verified'],
      dtype='object')

In [ ]:
# Extract text from PDF file

# Path to the job description PDF

# Path to folder containing PDF

# Extract text from job desription

# Collect resumes and their text

# Use TF-IDF vertorization to convert text to numerical representation

# Calculate cosine similarity between job and resume